### ISSUE TITLE
React Content

### ISSUE THREAD

**Issue by yracnet** [Enet4/es-get-exports#1]
I tried use this lib with a file with React,

this trows the expcetion: 

`SyntaxError: Unexpected token <`

for a file like to:

`export const Tag = ()=> <h1>Test</h1>`

**Comment by Enet4** [comment]
Sorry, but jsx files are not supported and I don't believe that I'll be able to maintain this package. If this specific task is important, I would suggest picking an up to date JavaScript source code parser and working with it to identify exports.

**Comment by yracnet** [comment]
Thanks, your plugin helps a lot.
